fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\DarwinApp\UserManagement\Domain\Entity\User
  service:
    mailer: 'fos_user.mailer.noop'
  from_email:
    address: "team@darwin.com"
    sender_name: "Darwin Team"
