vich_uploader:
    db_driver: orm

    mappings:
        post_image:
            uri_prefix: '/uploads/post_images'
            upload_destination: '%kernel.project_dir%/public/images/post_images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
