darwin_app.post_management.presentation.edit_post:
  path:     /posts/{id}/edit
  controller: App\DarwinApp\PostManagement\Presentation\Controller\PostManagementController::editPostAction
  methods:  [GET, PATCH]

darwin_app.post_management.presentation.delete_post:
  path:     /posts/{id}/delete
  controller: App\DarwinApp\PostManagement\Presentation\Controller\PostManagementController::deletePostAction
  methods:  [DELETE]

darwin_app.post_management.presentation.show_user_posts:
  path:     /users/{username}/posts
  controller: App\DarwinApp\PostManagement\Presentation\Controller\PostManagementController::showPostsOfUserAction
  methods:  [GET]
