fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_registration_register:
  path: /register
  controller: App\DarwinApp\UserManagement\Presentation\Controller\RegistrationController::registerAction
  methods: [GET, POST]
